In [2]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
from matplotlib import rcParams
import math
import matplotlib as mpl
import matplotlib as mp
import numpy as no
#importing all the neccessary libraries

In [3]:

ames_url = 'https://raw.githubusercontent.com/wblakecannon/ames/master/data/housing.csv'

ames = pd.read_csv(ames_url)

In [4]:
ames.head(5)

,Unnamed: 0,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [5]:
len(ames)
# it is used to tell the lenght of the data which is given to us

2930

In [6]:
ames.describe

<bound method NDFrame.describe of       Unnamed: 0  Order        PID  MS SubClass MS Zoning  Lot Frontage  \
0              0      1  526301100           20        RL         141.0
1              1      2  526350040           20        RH          80.0
2              2      3  526351010           20        RL          81.0
3              3      4  526353030           20        RL          93.0
4              4      5  527105010           60        RL          74.0
...          ...    ...        ...          ...       ...           ...
2925        2925   2926  923275080           80        RL          37.0
2926        2926   2927  923276100           20        RL           NaN
2927        2927   2928  923400125           85        RL          62.0
2928        2928   2929  924100070           20        RL          77.0
2929        2929   2930  924151050           60        RL          74.0

      Lot Area Street Alley Lot Shape  ... Pool Area Pool QC  Fence  \
0        31770   Pave   NaN       IR1  ...         0     NaN    NaN
1        11622   Pave   NaN       Reg  ...         0     NaN  MnPrv
2        14267   Pave   NaN       IR1  ...         0     NaN    NaN
3        11160   Pave   NaN       Reg  ...         0     NaN    NaN
4        13830   Pave   NaN       IR1  ...         0     NaN  MnPrv
...        ...    ...   ...       ...  ...       ...     ...    ...
2925      7937   Pave   NaN       IR1  ...         0     NaN  GdPrv
2926      8885   Pave   NaN       IR1  ...         0     NaN  MnPrv
2927     10441   Pave   NaN       Reg  ...         0     NaN  MnPrv
2928     10010   Pave   NaN       Reg  ...         0     NaN    NaN
2929      9627   Pave   NaN       Reg  ...         0     NaN    NaN

     Misc Feature Misc Val Mo Sold Yr Sold Sale Type Sale Condition  SalePrice
0             NaN        0       5    2010       WD          Normal     215000
1             NaN        0       6    2010       WD          Normal     105000
2            Gar2    12500       6    2010       WD          Normal     172000
3             NaN        0       4    2010       WD          Normal     244000
4             NaN        0       3    2010       WD          Normal     189900
...           ...      ...     ...     ...       ...            ...        ...
2925          NaN        0       3    2006       WD          Normal     142500
2926          NaN        0       6    2006       WD          Normal     131000
2927         Shed      700       7    2006       WD          Normal     132000
2928          NaN        0       4    2006       WD          Normal     170000
2929          NaN        0      11    2006       WD          Normal     188000

[2930 rows x 83 columns]>

In [7]:
pd.options.display.max_columns = 100
print(ames)

      Unnamed: 0  Order        PID  MS SubClass MS Zoning  Lot Frontage  \
0              0      1  526301100           20        RL         141.0
1              1      2  526350040           20        RH          80.0
2              2      3  526351010           20        RL          81.0
3              3      4  526353030           20        RL          93.0
4              4      5  527105010           60        RL          74.0
...          ...    ...        ...          ...       ...           ...
2925        2925   2926  923275080           80        RL          37.0
2926        2926   2927  923276100           20        RL           NaN
2927        2927   2928  923400125           85        RL          62.0
2928        2928   2929  924100070           20        RL          77.0
2929        2929   2930  924151050           60        RL          74.0

      Lot Area Street Alley Lot Shape Land Contour Utilities Lot Config  \
0        31770   Pave   NaN       IR1          Lvl    AllPub     Corner
1        11622   Pave   NaN       Reg          Lvl    AllPub     Inside
2        14267   Pave   NaN       IR1          Lvl    AllPub     Corner
3        11160   Pave   NaN       Reg          Lvl    AllPub     Corner
4        13830   Pave   NaN       IR1          Lvl    AllPub     Inside
...        ...    ...   ...       ...          ...       ...        ...
2925      7937   Pave   NaN       IR1          Lvl    AllPub    CulDSac
2926      8885   Pave   NaN       IR1          Low    AllPub     Inside
2927     10441   Pave   NaN       Reg          Lvl    AllPub     Inside
2928     10010   Pave   NaN       Reg          Lvl    AllPub     Inside
2929      9627   Pave   NaN       Reg          Lvl    AllPub     Inside

     Land Slope Neighborhood Condition 1 Condition 2 Bldg Type House Style  \
0           Gtl        NAmes        Norm        Norm      1Fam      1Story
1           Gtl        NAmes       Feedr        Norm      1Fam      1Story
2           Gtl        NAmes        Norm        Norm      1Fam      1Story
3           Gtl        NAmes        Norm        Norm      1Fam      1Story
4           Gtl      Gilbert        Norm        Norm      1Fam      2Story
...         ...          ...         ...         ...       ...         ...
2925        Gtl      Mitchel        Norm        Norm      1Fam        SLvl
2926        Mod      Mitchel        Norm        Norm      1Fam      1Story
2927        Gtl      Mitchel        Norm        Norm      1Fam      SFoyer
2928        Mod      Mitchel        Norm        Norm      1Fam      1Story
2929        Mod      Mitchel        Norm        Norm      1Fam      2Story

      Overall Qual  Overall Cond  Year Built  Year Remod/Add Roof Style  \
0                6             5        1960            1960        Hip
1                5             6        1961            1961      Gable
2                6             6        1958            1958        Hip
3                7             5        1968            1968        Hip
4                5             5        1997            1998      Gable
...            ...           ...         ...             ...        ...
2925             6             6        1984            1984      Gable
2926             5             5        1983            1983      Gable
2927             5             5        1992            1992      Gable
2928             5             5        1974            1975      Gable
2929             7             5        1993            1994      Gable

     Roof Matl Exterior 1st Exterior 2nd Mas Vnr Type  Mas Vnr Area  \
0      CompShg      BrkFace      Plywood        Stone         112.0
1      CompShg      VinylSd      VinylSd          NaN           0.0
2      CompShg      Wd Sdng      Wd Sdng      BrkFace         108.0
3      CompShg      BrkFace      BrkFace          NaN           0.0
4      CompShg      VinylSd      VinylSd          NaN           0.0
...        ...          ...          ...          ...           ...
2925   CompShg      HdBoard      HdBoard          NaN           0.0
2926   CompShg      HdBoard      HdBoard          NaN           0.0
2927   CompShg      HdBoard      Wd Shng          NaN           0.0
2928   CompShg      HdBoard      HdBoard          NaN           0.0
2929   CompShg      HdBoard      HdBoard      BrkFace          94.0

     Exter Qual Exter Cond Foundation Bsmt Qual Bsmt Cond Bsmt Exposure  \
0            TA         TA     CBlock        TA        Gd            Gd
1            TA         TA     CBlock        TA        TA            No
2            TA         TA     CBlock        TA        TA            No
3            Gd         TA     CBlock        TA        TA            No
4            TA         TA      PConc        Gd        TA            No
...         ...        ...        ...       ...       ...           ...
2925         TA         TA     CBlock        TA        TA            Av
2926         TA         TA     CBlock        Gd        TA            Av
2927         TA         TA      PConc        Gd        TA            Av
2928         TA         TA     CBlock        Gd        TA            Av
2929         TA         TA      PConc        Gd        TA            Av

     BsmtFin Type 1  BsmtFin SF 1 BsmtFin Type 2  BsmtFin SF 2  Bsmt Unf SF  \
0               BLQ         639.0            Unf           0.0        441.0
1               Rec         468.0            LwQ         144.0        270.0
2               ALQ         923.0            Unf           0.0        406.0
3               ALQ        1065.0            Unf           0.0       1045.0
4               GLQ         791.0            Unf           0.0        137.0
...             ...           ...            ...           ...          ...
2925            GLQ         819.0            Unf           0.0        184.0
2926            BLQ         301.0            ALQ         324.0        239.0
2927            GLQ         337.0            Unf           0.0        575.0
2928            ALQ        1071.0            LwQ         123.0        195.0
2929            LwQ         758.0            Unf           0.0        238.0

      Total Bsmt SF Heating Heating QC Central Air Electrical  1st Flr SF  \
0            1080.0    GasA         Fa           Y      SBrkr        1656
1             882.0    GasA         TA           Y      SBrkr         896
2            1329.0    GasA         TA           Y      SBrkr        1329
3            2110.0    GasA         Ex           Y      SBrkr        2110
4             928.0    GasA         Gd           Y      SBrkr         928
...             ...     ...        ...         ...        ...         ...
2925         1003.0    GasA         TA           Y      SBrkr        1003
2926          864.0    GasA         TA           Y      SBrkr         902
2927          912.0    GasA         TA           Y      SBrkr         970
2928         1389.0    GasA         Gd           Y      SBrkr        1389
2929          996.0    GasA         Ex           Y      SBrkr         996

      2nd Flr SF  Low Qual Fin SF  Gr Liv Area  Bsmt Full Bath  \
0              0                0         1656             1.0
1              0                0          896             0.0
2              0                0         1329             0.0
3              0                0         2110             1.0
4            701                0         1629             0.0
...          ...              ...          ...             ...
2925           0                0         1003             1.0
2926           0                0          902             1.0
2927           0                0          970             0.0
2928           0                0         1389             1.0
2929        1004                0         2000             0.0

      Bsmt Half Bath  Full Bath  Half Bath  Bedroom AbvGr  Kitchen AbvGr  \
0                0.0          1          0              3              1
1                0.0          1          0              2              1
2                0.0          1          1              3              1
3                0.0          2          1              3              1
4                0.0          2          1              3              1
...              ...        ...        ...            ...            ...
2925             0.0          1          0              3              1
2926             0.0          1          0              2              1
2927             1.0          1          0              3              1
2928             0.0          1          0              2              1
2929             0.0          2          1              3              1

     Kitchen Qual  TotRms AbvGrd Functional  Fireplaces Fireplace Qu  \
0              TA              7        Typ           2           Gd
1              TA              5        Typ           0          NaN
2              Gd              6        Typ           0          NaN
3              Ex              8        Typ           2           TA
4              TA              6        Typ           1           TA
...           ...            ...        ...         ...          ...
2925           TA              6        Typ           0          NaN
2926           TA              5        Typ           0          NaN
2927           TA              6        Typ           0          NaN
2928           TA              6        Typ           1           TA
2929           TA              9        Typ           1           TA

     Garage Type  Garage Yr Blt Garage Finish  Garage Cars  Garage Area  \
0         Attchd         1960.0           Fin          2.0        528.0
1         Attchd         1961.0           Unf          1.0        730.0
2         Attchd         1958.0           Unf          1.0        312.0
3         Attchd         1968.0           Fin          2.0        522.0
4         Attchd         1997.0           Fin          2.0        482.0
...          ...            ...           ...          ...          ...
2925      Detchd         1984.0           Unf          2.0        588.0
2926      Attchd         1983.0           Unf          2.0        484.0
2927         NaN            NaN           NaN          0.0          0.0
2928      Attchd         1975.0           RFn          2.0        418.0
2929      Attchd         1993.0           Fin          3.0        650.0

     Garage Qual Garage Cond Paved Drive  Wood Deck SF  Open Porch SF  \
0             TA          TA           P           210             62
1             TA          TA           Y           140              0
2             TA          TA           Y           393             36
3             TA          TA           Y             0              0
4             TA          TA           Y           212             34
...          ...         ...         ...           ...            ...
2925          TA          TA           Y           120              0
2926          TA          TA           Y           164              0
2927         NaN         NaN           Y            80             32
2928          TA          TA           Y           240             38
2929          TA          TA           Y           190             48

      Enclosed Porch  3Ssn Porch  Screen Porch  Pool Area Pool QC  Fence  \
0                  0           0             0          0     NaN    NaN
1                  0           0           120          0     NaN  MnPrv
2                  0           0             0          0     NaN    NaN
3                  0           0             0          0     NaN    NaN
4                  0           0             0          0     NaN  MnPrv
...              ...         ...           ...        ...     ...    ...
2925               0           0             0          0     NaN  GdPrv
2926               0           0             0          0     NaN  MnPrv
2927               0           0             0          0     NaN  MnPrv
2928               0           0             0          0     NaN    NaN
2929               0           0             0          0     NaN    NaN

     Misc Feature  Misc Val  Mo Sold  Yr Sold Sale Type Sale Condition  \
0             NaN         0        5     2010       WD          Normal
1             NaN         0        6     2010       WD          Normal
2            Gar2     12500        6     2010       WD          Normal
3             NaN         0        4     2010       WD          Normal
4             NaN         0        3     2010       WD          Normal
...           ...       ...      ...      ...       ...            ...
2925          NaN         0        3     2006       WD          Normal
2926          NaN         0        6     2006       WD          Normal
2927         Shed       700        7     2006       WD          Normal
2928          NaN         0        4     2006       WD          Normal
2929          NaN         0       11     2006       WD          Normal

      SalePrice
0        215000
1        105000
2        172000
3        244000
4        189900
...         ...
2925     142500
2926     131000
2927     132000
2928     170000
2929     188000

[2930 rows x 83 columns]

In [8]:
ames.describe()
ames.describe().round(1)
# here we have used the round function which basically rounds the values to the nearest 1st decimal

,Unnamed: 0,Order,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,TotRms AbvGrd,Fireplaces,Garage Yr Blt,Garage Cars,Garage Area,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
count,2930.0,2930.0,2.930000e+03,2930.0,2440.0,2930.0,2930.0,2930.0,2930.0,2930.0,2907.0,2929.0,2929.0,2929.0,2929.0,2930.0,2930.0,2930.0,2930.0,2928.0,2928.0,2930.0,2930.0,2930.0,2930.0,2930.0,2930.0,2771.0,2929.0,2929.0,2930.0,2930.0,2930.0,2930.0,2930.0,2930.0,2930.0,2930.0,2930.0,2930.0
mean,1464.5,1465.5,7.144645e+08,57.4,69.2,10147.9,6.1,5.6,1971.4,1984.3,101.9,442.6,49.7,559.3,1051.6,1159.6,335.5,4.7,1499.7,0.4,0.1,1.6,0.4,2.9,1.0,6.4,0.6,1978.1,1.8,472.8,93.8,47.5,23.0,2.6,16.0,2.2,50.6,6.2,2007.8,180796.1
std,846.0,846.0,1.887308e+08,42.6,23.4,7880.0,1.4,1.1,30.2,20.9,179.1,455.6,169.2,439.5,440.6,391.9,428.4,46.3,505.5,0.5,0.2,0.6,0.5,0.8,0.2,1.6,0.6,25.5,0.8,215.0,126.4,67.5,64.1,25.1,56.1,35.6,566.3,2.7,1.3,79886.7
min,0.0,1.0,5.263011e+08,20.0,21.0,1300.0,1.0,1.0,1872.0,1950.0,0.0,0.0,0.0,0.0,0.0,334.0,0.0,0.0,334.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,1895.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2006.0,12789.0
25%,732.2,733.2,5.284770e+08,20.0,58.0,7440.2,5.0,5.0,1954.0,1965.0,0.0,0.0,0.0,219.0,793.0,876.2,0.0,0.0,1126.0,0.0,0.0,1.0,0.0,2.0,1.0,5.0,0.0,1960.0,1.0,320.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,2007.0,129500.0
50%,1464.5,1465.5,5.354536e+08,50.0,68.0,9436.5,6.0,5.0,1973.0,1993.0,0.0,370.0,0.0,466.0,990.0,1084.0,0.0,0.0,1442.0,0.0,0.0,2.0,0.0,3.0,1.0,6.0,1.0,1979.0,2.0,480.0,0.0,27.0,0.0,0.0,0.0,0.0,0.0,6.0,2008.0,160000.0
75%,2196.8,2197.8,9.071811e+08,70.0,80.0,11555.2,7.0,6.0,2001.0,2004.0,164.0,734.0,0.0,802.0,1302.0,1384.0,703.8,0.0,1742.8,1.0,0.0,2.0,1.0,3.0,1.0,7.0,1.0,2002.0,2.0,576.0,168.0,70.0,0.0,0.0,0.0,0.0,0.0,8.0,2009.0,213500.0
max,2929.0,2930.0,1.007100e+09,190.0,313.0,215245.0,10.0,9.0,2010.0,2010.0,1600.0,5644.0,1526.0,2336.0,6110.0,5095.0,2065.0,1064.0,5642.0,3.0,2.0,4.0,2.0,8.0,3.0,15.0,4.0,2207.0,5.0,1488.0,1424.0,742.0,1012.0,508.0,576.0,800.0,17000.0,12.0,2010.0,755000.0

In [9]:
ames.isnull().sum()
# here we have used to clean the given data

Unnamed: 0        0
Order             0
PID               0
MS SubClass       0
MS Zoning         0
                 ..
Mo Sold           0
Yr Sold           0
Sale Type         0
Sale Condition    0
SalePrice         0
Length: 83, dtype: int64

In [10]:
from IPython.display import FileLink

In [11]:
cleaned_file_path = 'cleaned_housing_data.csv'
ames.to_csv(cleaned_file_path, index=False)
FileLink(cleaned_file_path)

/Users/Lenovo/Desktop/4 sem/data-cleaning-and-house-cost-calculation-model/cleaned_housing_data.csv

# here we have got the cleaned csv file , which we are now going to use and import in the given area

In [12]:
ames.iloc[:,[5,6,7,82]].describe().round(1)
# this takes the 5 , 6, 7 , 82 columns and describes them

       Lot Frontage  Lot Area  SalePrice
count        2440.0    2930.0     2930.0
mean           69.2   10147.9   180796.1
std            23.4    7880.0    79886.7
min            21.0    1300.0    12789.0
25%            58.0    7440.2   129500.0
50%            68.0    9436.5   160000.0
75%            80.0   11555.2   213500.0
max           313.0  215245.0   755000.0

In [13]:
ames.head(5)

,Unnamed: 0,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Fireplace Qu,Garage Type,Garage Yr Blt,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,5,1960,1960,Hip,CompShg,BrkFace,Plywood,Stone,112.0,TA,TA,CBlock,TA,Gd,Gd,BLQ,639.0,Unf,0.0,441.0,1080.0,GasA,Fa,Y,SBrkr,1656,0,0,1656,1.0,0.0,1,0,3,1,TA,7,Typ,2,Gd,Attchd,1960.0,Fin,2.0,528.0,TA,TA,P,210,62,0,0,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,Norm,1Fam,1Story,5,6,1961,1961,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,CBlock,TA,TA,No,Rec,468.0,LwQ,144.0,270.0,882.0,GasA,TA,Y,SBrkr,896,0,0,896,0.0,0.0,1,0,2,1,TA,5,Typ,0,NaN,Attchd,1961.0,Unf,1.0,730.0,TA,TA,Y,140,0,0,0,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,6,1958,1958,Hip,CompShg,Wd Sdng,Wd Sdng,BrkFace,108.0,TA,TA,CBlock,TA,TA,No,ALQ,923.0,Unf,0.0,406.0,1329.0,GasA,TA,Y,SBrkr,1329,0,0,1329,0.0,0.0,1,1,3,1,Gd,6,Typ,0,NaN,Attchd,1958.0,Unf,1.0,312.0,TA,TA,Y,393,36,0,0,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,7,5,1968,1968,Hip,CompShg,BrkFace,BrkFace,NaN,0.0,Gd,TA,CBlock,TA,TA,No,ALQ,1065.0,Unf,0.0,1045.0,2110.0,GasA,Ex,Y,SBrkr,2110,0,0,2110,1.0,0.0,2,1,3,1,Ex,8,Typ,2,TA,Attchd,1968.0,Fin,2.0,522.0,TA,TA,Y,0,0,0,0,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,5,5,1997,1998,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,PConc,Gd,TA,No,GLQ,791.0,Unf,0.0,137.0,928.0,GasA,Gd,Y,SBrkr,928,701,0,1629,0.0,0.0,2,1,3,1,TA,6,Typ,1,TA,Attchd,1997.0,Fin,2.0,482.0,TA,TA,Y,212,34,0,0,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [14]:
ames.loc[: ,['Pool QC', 'Fence', 'Misc Feature', 'Alley', 'Fireplace Qu']]

     Pool QC  Fence Misc Feature Alley Fireplace Qu
0        NaN    NaN          NaN   NaN           Gd
1        NaN  MnPrv          NaN   NaN          NaN
2        NaN    NaN         Gar2   NaN          NaN
3        NaN    NaN          NaN   NaN           TA
4        NaN  MnPrv          NaN   NaN           TA
...      ...    ...          ...   ...          ...
2925     NaN  GdPrv          NaN   NaN          NaN
2926     NaN  MnPrv          NaN   NaN          NaN
2927     NaN  MnPrv         Shed   NaN          NaN
2928     NaN    NaN          NaN   NaN           TA
2929     NaN    NaN          NaN   NaN           TA

[2930 rows x 5 columns]

In [15]:
# we are now going to make a model for the give dataset
ames_new= ames.drop(columns=['Alley' , 'Utilities' , 'Lot Shape' ,'Land Contour' ,'Land Slope' ])
ames_new
# removing the uncc

,Unnamed: 0,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Config,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Fireplace Qu,Garage Type,Garage Yr Blt,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,0,1,526301100,20,RL,141.0,31770,Pave,Corner,NAmes,Norm,Norm,1Fam,1Story,6,5,1960,1960,Hip,CompShg,BrkFace,Plywood,Stone,112.0,TA,TA,CBlock,TA,Gd,Gd,BLQ,639.0,Unf,0.0,441.0,1080.0,GasA,Fa,Y,SBrkr,1656,0,0,1656,1.0,0.0,1,0,3,1,TA,7,Typ,2,Gd,Attchd,1960.0,Fin,2.0,528.0,TA,TA,P,210,62,0,0,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,1,2,526350040,20,RH,80.0,11622,Pave,Inside,NAmes,Feedr,Norm,1Fam,1Story,5,6,1961,1961,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,CBlock,TA,TA,No,Rec,468.0,LwQ,144.0,270.0,882.0,GasA,TA,Y,SBrkr,896,0,0,896,0.0,0.0,1,0,2,1,TA,5,Typ,0,NaN,Attchd,1961.0,Unf,1.0,730.0,TA,TA,Y,140,0,0,0,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,2,3,526351010,20,RL,81.0,14267,Pave,Corner,NAmes,Norm,Norm,1Fam,1Story,6,6,1958,1958,Hip,CompShg,Wd Sdng,Wd Sdng,BrkFace,108.0,TA,TA,CBlock,TA,TA,No,ALQ,923.0,Unf,0.0,406.0,1329.0,GasA,TA,Y,SBrkr,1329,0,0,1329,0.0,0.0,1,1,3,1,Gd,6,Typ,0,NaN,Attchd,1958.0,Unf,1.0,312.0,TA,TA,Y,393,36,0,0,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,3,4,526353030,20,RL,93.0,11160,Pave,Corner,NAmes,Norm,Norm,1Fam,1Story,7,5,1968,1968,Hip,CompShg,BrkFace,BrkFace,NaN,0.0,Gd,TA,CBlock,TA,TA,No,ALQ,1065.0,Unf,0.0,1045.0,2110.0,GasA,Ex,Y,SBrkr,2110,0,0,2110,1.0,0.0,2,1,3,1,Ex,8,Typ,2,TA,Attchd,1968.0,Fin,2.0,522.0,TA,TA,Y,0,0,0,0,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,4,5,527105010,60,RL,74.0,13830,Pave,Inside,Gilbert,Norm,Norm,1Fam,2Story,5,5,1997,1998,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,PConc,Gd,TA,No,GLQ,791.0,Unf,0.0,137.0,928.0,GasA,Gd,Y,SBrkr,928,701,0,1629,0.0,0.0,2,1,3,1,TA,6,Typ,1,TA,Attchd,1997.0,Fin,2.0,482.0,TA,TA,Y,212,34,0,0,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2925,2926,923275080,80,RL,37.0,7937,Pave,CulDSac,Mitchel,Norm,Norm,1Fam,SLvl,6,6,1984,1984,Gable,CompShg,HdBoard,HdBoard,NaN,0.0,TA,TA,CBlock,TA,TA,Av,GLQ,819.0,Unf,0.0,184.0,1003.0,GasA,TA,Y,SBrkr,1003,0,0,1003,1.0,0.0,1,0,3,1,TA,6,Typ,0,NaN,Detchd,1984.0,Unf,2.0,588.0,TA,TA,Y,120,0,0,0,0,0,NaN,GdPrv,NaN,0,3,2006,WD,Normal,142500
2926,2926,2927,923276100,20,RL,NaN,8885,Pave,Inside,Mitchel,Norm,Norm,1Fam,1Story,5,5,1983,1983,Gable,CompShg,HdBoard,HdBoard,NaN,0.0,TA,TA,CBlock,Gd,TA,Av,BLQ,301.0,ALQ,324.0,239.0,864.0,GasA,TA,Y,SBrkr,902,0,0,902,1.0,0.0,1,0,2,1,TA,5,Typ,0,NaN,Attchd,1983.0,Unf,2.0,484.0,TA,TA,Y,164,0,0,0,0,0,NaN,MnPrv,NaN,0,6,2006,WD,Normal,131000
2927,2927,2928,923400125,85,RL,62.0,10441,Pave,Inside,Mitchel,Norm,Norm,1Fam,SFoyer,5,5,1992,1992,Gable,CompShg,HdBoard,Wd Shng,NaN,0.0,TA,TA,PConc,Gd,TA,Av,GLQ,337.0,Unf,0.0,575.0,912.0,GasA,TA,Y,SBrkr,970,0,0,970,0.0,1.0,1,0,3,1,TA,6,Typ,0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,Y,80,32,0,0,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,132000
2928,2928,2929,924100070,20,RL,77.0,10010,Pave,Inside,Mitchel,Norm,Norm,1Fam,1Story,5,5,1974,1975,Gable,CompShg,HdBoard,HdBoard,NaN,0.0,TA,TA,CBlock,Gd,TA,Av,ALQ,1071.0,LwQ,123.0,195.0,1389.0,GasA,Gd,Y,SBrkr,1389,0,0,1389,1.0,0.0,1,0,2,1,TA,6,Typ,1,TA,Attchd,1975.0,RFn,2.0,418.0,TA,TA,Y,240,38,0,0,0,0,NaN,NaN,NaN,0,4,2006,WD,Normal,170000
2929,2929,2930,924151050,60,RL,74.0,9627,Pave,Inside,Mitchel,Norm,Norm,1Fam,2Story,7,5,1993,1994,Gable,CompShg,HdBoard,HdBoard,BrkFace,94.0,TA,TA,PConc,Gd,TA,Av,LwQ,758.0,Unf,0.0,238.0,996.0,GasA,Ex,Y,SBrkr,996,1004,0,2000,0.0,0.0,2,1,3,1,TA,9,Typ,1,TA,Attchd,1993.0,Fin,3.0,650.0,TA,TA,Y,190,48,0,0,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal,188000

In [16]:
selected_columns = ['Order', 'Lot Frontage' ,'Lot Frontage' ,'Garage Area', 'House Style' ,'Fireplaces' ,'Garage Type' ,'Garage Cars','Yr Sold','SalePrice' ]
new_dataset = ames[selected_columns]
new_dataset.head(5)

,Order,Lot Frontage,Lot Frontage,Garage Area,House Style,Fireplaces,Garage Type,Garage Cars,Yr Sold,SalePrice
0,1,141.0,141.0,528.0,1Story,2,Attchd,2.0,2010,215000
1,2,80.0,80.0,730.0,1Story,0,Attchd,1.0,2010,105000
2,3,81.0,81.0,312.0,1Story,0,Attchd,1.0,2010,172000
3,4,93.0,93.0,522.0,1Story,2,Attchd,2.0,2010,244000
4,5,74.0,74.0,482.0,2Story,1,Attchd,2.0,2010,189900

In [17]:
cleaned_file_path = 'new_housing_data.csv'
new_dataset.to_csv(cleaned_file_path, index=False)
FileLink(cleaned_file_path)

/Users/Lenovo/Desktop/4 sem/data-cleaning-and-house-cost-calculation-model/new_housing_data.csv

In [18]:
new_dataset.shape
# this is used to tell the shape of the given dataset we have
# this means we have 2930 rows and 10 columns

(2930, 10)